<!--   $Header: /nfs/slac/g/glast/ground/cvs/calibUtil/xml/badStrips.dtd,v 1.8 2003/07/11 19:32:30 jrb Exp $   /**  @file       badStrips.dtd        @authors    J. Bogart        dtd for bad strips data file    */    Would be good to switch to schema so that common header elements    could be included easily in schema for different calibration types. -->       <!-- Container for all the header/metadata type information to be     included here.  Complete metadata will be found in the calibration     MySQL database.      Description of attributes:            instrument    - one of "flight", "EM", etc.  Could also                            be implemented as enumeration rather than                            NMTOKEN            timestamp     - when the file was written (date and time)            calType       - one of "TKRBadStrips", "CALLightAttenuation",                            etc.            formatVersion - sufficient versioning information so that                            software attempting to read the file can                            determine if it supports this version.                             [Might get rid of this here and just keep                            it in the MySQL metadata table] --><!DOCTYPE badStrips [<!ELEMENT badStrips (generic, cuts?, tower*) ><!ATTLIST badStrips badType (hot | dead) #REQUIRED ><!ELEMENT  generic  (inputSample) ><!ATTLIST generic     instrument  (LAT | BFEM | BTEM | EM | CU) #REQUIRED   timestamp   NMTOKEN #REQUIRED   calType     NMTOKEN #REQUIRED   DTDVersion  NMTOKEN "v3r1"          fmtVersion  NMTOKEN #REQUIRED ><!-- Description of events used as input to the procedure      Start- and stop-times should be timestamps of earliest and     latest events included in sample--><!ELEMENT inputSample (#PCDATA) ><!ATTLIST inputSample  startTime NMTOKEN #REQUIRED                       stopTime  NMTOKEN #REQUIRED                       triggers  NMTOKENS #REQUIRED                        source    NMTOKENS #REQUIRED                       mode      NMTOKEN  #REQUIRED><!-- "tight", "loose" and "expected" are all expressed as percentage     of events for which a strip is hit, and all are affected by the     kind of event sample.     "expected" is the percentage expected for a healthy channel.     "tight" will be somewhat more than "expected" if we're looking     for hot channels, less than "expected" if we're looking for     dead.     "loose" will be further from "expected" than "tight", but in the     same direction.     --><!ELEMENT cuts EMPTY><!ATTLIST cuts  tight       NMTOKEN #REQUIRED                loose       NMTOKEN #REQUIRED                expected    NMTOKEN #REQUIRED ><!-- Towers are identified by row and column (least subject     to misinterpretation for different instruments      Only include towers for which there is at least one     tray with bad strips     To mark all strips in a tower as bad in the same way, set     one or more of the attributes nOnbdCalib, nOnbdTrig, nOnbdData      to "true".  These are meant to correspond to similarly named     bits in the hardware.     See also <uniplane>, which has the same collection of attributes     Meanings are:           nOnbdCalib   - not usable for charge injection calibration           nOnbdTrig     - not usable by trigger           nOnbdData     - not usable for recon, data analysis --><!ELEMENT tower (uniplane*) ><!ATTLIST tower row NMTOKEN #REQUIRED                 col NMTOKEN #REQUIRED                 nOnbdCalib  (true | false) "false"                nOnbdTrig    (true | false) "false"                nOnbdData    (true | false) "false"  ><!-- Each uniplane is identified by a tray # (zero based, back-most tray      is tray 0, according to Steve Ritz convention) and top/bottom      field.   A uniplane is either all bad or specifies which strips      are bad.  Within a givin tower, there should be at most one      instance of a particular uniplane whose strips are a particular      "badness", but dtd can't enforce this constraint.  --><!ELEMENT uniplane (stripList?, stripSpan?)* ><!ATTLIST uniplane tray      NMTOKEN #REQUIRED                   which       (top | bot) #REQUIRED                   nOnbdCalib  (true | false) "false"                   nOnbdTrig   (true | false) "false"                   nOnbdData   (true | false) "false"                     allBad      (true | false) "false" ><!-- For each plane containing bad strips of a particular badness,     include a list or span(s)  of affected strips, or mark it     as all bad. --><!ELEMENT stripList EMPTY ><!ATTLIST stripList strips NMTOKENS #REQUIRED ><!ELEMENT stripSpan EMPTY ><!ATTLIST stripSpan first NMTOKEN #REQUIRED                    last  NMTOKEN #REQUIRED >] >
<badStrips badType= "dead">
   <generic instrument="EM" timestamp="2003-11-7-18:00" calType="TkrBadStrips" fmtVersion="v2r0" >
      <inputSample startTime="2003-10-1-00:00" stopTime="2003-12-1-00:00" triggers="physics" mode="normal" source="VDG" >
         Output from BadStripsCalib, on run ebf031006235353
      </inputSample>
   </generic>
   <tower row="0" col="0">
      <uniplane tray="0" which="top"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  allBad="true" />
      <uniplane tray="1" which="bot"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  allBad="true" />
      <uniplane tray="1" which="top"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  >
         <stripList strips= " 434 " />
      </uniplane>
      <uniplane tray="2" which="bot"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  >
         <stripSpan first= "0" last= "33" />
         <stripList strips= " 107 122 578 " />
         <stripSpan first= "1151" last= "1535" />
      </uniplane>
      <uniplane tray="2" which="top"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  >
         <stripList strips= " 561 1073 1445 1449 1464 1487 " />
      </uniplane>
      <uniplane tray="3" which="bot"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  >
         <stripList strips= " 21 66 67 810 812 862 971 1024 1081 1087 
                    1117 1153 1154 1155 1164 " />
         <stripSpan first= "1170" last= "1199" />
         <stripList strips= " 1203 1204 1205 1206 1209 1312 1329 1343 1373 1399 
                    1410 1411 1412 1413 1420 1421 1422 1423 1424 1425 
                    1426 1432 1433 1434 1447 1468 1469 1470 1471 1523 
                    1530 1531 1532 " />
      </uniplane>
      <uniplane tray="3" which="top"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  >
         <stripList strips= " 1159 1374 1375 1376 1377 1378 1379 1380 1381 1382 
                    1383 " />
      </uniplane>
      <uniplane tray="4" which="bot"  nOnbdTrig="false" nOnbdCalib="false" nOnbdData="true"  >
         <stripSpan first= "0" last= "156" />
         <stripList strips= " 269 402 458 1059 1203 1219 1229 1250 " />
      </uniplane>
   </tower>
</badStrips>
